
import remotaskst from "../../Images/Remotasks.png";

interface SingleWorkExperience {
  positionEn: string;
  positionEs: string;
  organization: string;
  descriptionEn: string;
  descriptionEs: string;
  dateEn: string;
  dateEs: string;
  organizationIcon: string
}

export const AllWorkExperience: Array<SingleWorkExperience> = [
  {
    positionEn: "AI Trainer",
    positionEs: "Entrenador de IA",
    organization: "Remotasks",
    descriptionEn: "I evaluate and compare the code generated by this model based on predefined criteria. It is a rewarding experience that allows me to leverage my programming skills while contributing to the advancement of AI technology.",
    descriptionEs: "Evalúo y comparo el código generado por este modelo basándome en criterios predefinidos. Es una experiencia gratificante que me permite aprovechar mis conocimientos de programación a la vez que contribuyo al avance de la tecnología de IA.",
    dateEn: "01/2024 - Present",
    dateEs: "01/2024 - Presente",
    organizationIcon: remotaskst
  },
];
